
export const ADD_REPORT_REQUEST = 'ADD_REPORT_REQUEST'
export const ADD_REPORT_SUCCESS = 'ADD_REPORT_SUCCESS'
export const ADD_REPORT_FAILURE = 'ADD_REPORT_FAILURE'
//
export const GET_FIELD_REQUEST = 'GET_FIELD_REQUEST'
export const GET_FIELD_SUCCESS = 'GET_FIELD_SUCCESS'
export const GET_FIELD_FAILURE = 'GET_FIELD_FAILURE'
//
export const GET_PROBLEM_REQUEST = 'GET_PROBLEM_REQUEST'
export const GET_PROBLEM_SUCCESS = 'GET_PROBLEM_SUCCESS'
export const GET_PROBLEM_FAILURE = 'GET_PROBLEM_FAILURE'
//
export const GET_LOCATION_REQUEST = 'GET_LOCATION_REQUEST'
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS'
export const GET_LOCATION_FAILURE = 'GET_LOCATION_FAILURE'
//
export const GET_POSITIONS_REQUEST = 'GET_POSITIONS_REQUEST'
export const GET_POSITIONS_SUCCESS = 'GET_POSITIONS_SUCCESS'
export const GET_POSITIONS_FAILURE = 'GET_POSITIONS_FAILURE'
// comment
export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE'
